[workspace]
resolver = "3"
members = [ "apps/*"]


[workspace.dependencies]
mm1 = {version = "=0.6.2", features = ["message-format-json", "message-format-bincode", "message-format-rmp"] }
mm1-logger = "=0.6.2"
