codecs:
  - name: full

subnets:
  - net_address: <cafe:>/16
    type: local
  
  - net_address: <decaf:>/20
    type: remote
    codec: full
    protocol: wip
    serde: bincode
    link:
      bind: 127.0.0.1:12001
      peer: 127.0.0.1:12002
  
  - net_address: <bad:>/12
    type: remote
    codec: full
    protocol: wip
    serde: bincode
    link:
      bind: 127.0.0.1:12002
      peer: 127.0.0.1:12001

runtime:
  default:
    worker_threads: 2
  
  system:
    worker_threads: 1
  
  one:
    worker_threads: 1
  
  two:
    worker_threads: 2
  
  three:
    worker_threads: 3

actor:
  inbox_size: 128
  fork_inbox_size: 16
  /:
    mm1_name_service::server::name_server_actor:
      netmask: 60
      runtime: system
    mm1_multinode::remote_subnet::sup::run:
      netmask: 40
      runtime: system
    mm1_multinode::network_manager::network_manager_actor:
      netmask: 60
      runtime: system
    _:
      runtime: three
      /:  
        actor_hierarchy::child_1:
          runtime: one
          netmask: 52
          /:
            actor_hierarchy::child_a:
              netmask: 48
              runtime: three
        actor_hierarchy::child_2:
          runtime: two
    

